update Dockerfile, README.md, valheim_server_functions and valheim_up.sh

diff --git a/scripts/valheim_server_functions b/scripts/valheim_server_functions
--- a/scripts/valheim_server_functions
+++ b/scripts/valheim_server_functions
@@ -35,6 +35,30 @@ server_update () {
 
 }
 
+check_whitelist() {
+    if [ -n "$SERVER_ALLOW_LIST" ]; then
+        update_config_element "EnableWhitelist" "True"
+        
+        # Remove existing whitelist file if it exists
+        if [ -f "$STEAM_ALLOW_LIST_PATH" ]; then
+            rm "$STEAM_ALLOW_LIST_PATH" || { log "Failed to remove existing whitelist file: $STEAM_ALLOW_LIST_PATH"; return 1; }
+        fi
+        
+        # Create an empty whitelist file
+        touch "$STEAM_ALLOW_LIST_PATH" || { log "Failed to create whitelist file: $STEAM_ALLOW_LIST_PATH"; return 1; }
+        
+        # Populate whitelist file with STEAM_IDs
+        # Split SERVER_ALLOW_LIST on commas and iterate over each part
+        IFS=", " read -r -a STEAM_IDS <<< "$SERVER_ALLOW_LIST"
+        for STEAM_ID in "${STEAM_IDS[@]}"; do
+            echo "$STEAM_ID" >> "$STEAM_ALLOW_LIST_PATH" || { log "Failed to write to whitelist file: $STEAM_ALLOW_LIST_PATH"; return 1; }
+        done
+        
+        log "Allow list created:"
+        cat "$STEAM_ALLOW_LIST_PATH" | log_stdout
+    fi
+}
+
 server_start() {
 
     # Display server configuration
